### ISSUE TITLE
Can this be used in Mortal Kombat or Street Fighter?

### ISSUE THREAD

**Issue by clsource** [churchofrobotron/mame_cor#1]
I would really love to make a similar experience
like Church of Robotron. But with Mortal Kombat II or Street Fighter II.

Know game events like Player Character Selection, 
Who wins the Round, etc.

And get them via UPD.

I´m willing to pay for this kind of research.

Please, 
 It would be awesome :+1: 

Thanks :panda_face:

**Comment by bzztbomb** [comment]
Camilo:

Yes, the UDP code is generic and can be used with any game.  The work is
figuring out the breakpoints and watchpoints that are interesting to you.
This webpage may help guide you a bit on that front:
http://bzztbomb.com/blog/2013/03/23/use-mames-debugger-to-reverse-engineer-and-extend-old-games/

It's possible someone has done that work already.  Maybe look around for MK
cheats, some of them may have memory locations you need.

I'm not really available at the moment to work on MK.  Been busy with
Robotron.  We just had another installation last Friday!

Hope that helps!

**Comment by clsource** [comment]
Brian:

Thanks for replying and I´m glad Church of Robotron is doing great :D 

Please,  
if you know someone who can help me 
discovering the breakpoints and watchpoints, that would be awesome.

Cheers :beers: :heart:
