### ISSUE TITLE
Can't Compile on Mac

### ISSUE THREAD

**Issue by clsource** [churchofrobotron/mame_cor#2]
Hello, 
Im trying to compile under OSX Yosemite
Already installed SDL 1, SDL 2 and Syphon frameworks
under /Library/Frameworks

https://www.libsdl.org/
http://syphon.v002.info/

But when doing make throws this

```
In file included from src/lib/util/coretmpl.h:18:
src/lib/util/corealloc.h:75:19: error: replacement function 'operator new'
      cannot be declared 'inline' [-Werror,-Winline-new-delete]
ATTR_FORCE_INLINE inline void *operator new(std::size_t size) throw (std...
                  ^
src/lib/util/corealloc.h:76:19: error: replacement function 'operator new[]'
      cannot be declared 'inline' [-Werror,-Winline-new-delete]
ATTR_FORCE_INLINE inline void *operator new[](std::size_t size) throw (s...
                  ^
src/lib/util/corealloc.h:77:19: error: replacement function 'operator delete'
      cannot be declared 'inline' [-Werror,-Winline-new-delete]
ATTR_FORCE_INLINE inline void operator delete(void *ptr) throw() { if (p...
                  ^
src/lib/util/corealloc.h:78:19: error: replacement function 'operator delete[]'
      cannot be declared 'inline' [-Werror,-Winline-new-delete]
ATTR_FORCE_INLINE inline void operator delete[](void *ptr) throw() { if ...
                  ^
4 errors generated.
make: *** [obj/sdl64d/build/makedep.o] Error 1
```

any help would me much appreciated :D
thanks.

**Comment by bzztbomb** [comment]
Not sure, it compiles for me, but I'm running 10.9 at the moment.  It is possible that merging the latest version of MAME would solve this.

**Comment by clsource** [comment]
Well that worked, 
I successfully compiled using mame 0.159
But when trying executing

`./mame64d -window -debug -di -debugscript debugscript.txt robotron`

says

`Unknown system 'debugscript.txt'
"debugscript.txt" approximately matches the following`

Futher investigations tells that the command

 `mame  ./mame64d -window -debug -di`

says
`Error: unknown option: -di`

When mergin robotron hacks with mame 0.159
I checked the following files for changes

./debug
./debug/debugcmd.c
./debug/debugcmd.h
./debugint
./debugint/debugint.c
./debugint/debugint.h
./emu.mak
./machine.c
./machine.h
./mcor_send.c
./mcor_send.h

Is there any other files that I should check for mame_cor
hacks? for updating the mame version.

Thanks :D

**Comment by bzztbomb** [comment]
Ah bummer, I wonder if the MAME team has dropped -di with the new release.
That would be annoying.  If I remember correctly, -di forced the debugger
to render with the MAME gui instead of a windowing toolkit (so QT on OSX).
Our hacked patch would then disable rendering for the MAME native
debugger.  It was nice to do this so we could launch the game with the
debugger enabled, but without the UI.  For now, you can drop -di and just
see if it works.

The debugscript.txt is this file:
https://github.com/bzztbomb/mame_cor/blob/cor/debugscript.txt which is the
debugger commands that set up the breakpoints.

**Comment by clsource** [comment]
I was able to compile mame_cor (and mame 0.153), 
modifying the makefile by disabling all warnings.
not the best practice, but works.

```
524 # add the error warning flag
525 ifndef NOWERROR
526 #CCOMFLAGS += -Werror
527 CCOMFLAGS += -w
528 endif
```

![captura de pantalla 2015-03-14 a las 13 29 21](https://cloud.githubusercontent.com/assets/292738/6652453/33ba5720-ca4e-11e4-9eeb-1e33c8f26709.png)

Hooray!

**Comment by clsource** [comment]
Also I was unable to listen to robotron events
but then I changed the debugscript

from

```
mcor_init 127.0.0.1, 127.0.0.255
```

to

```
mcor_init 127.0.0.1, 192.168.0.101
```

And openen 2084 for UDP in my home router so I was able to listen the events in the same computer.

Now Is all set :dancers: 

Thanks for your help :heart:

**Comment by bzztbomb** [comment]
hah! That is awesome!
